baseURL = 'https://rachelwhaley.github.io/'
languageCode = 'en-us'
title = 'Intro to Excel Workshop'

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[markup.goldmark.renderer]
    unsafe = true

[[menu.primary]]
    name  = "Docs"
    url = "/docs/"
    identifier = "docs"
    weight = 10

[caches]
  [caches.images]
    dir = ':cacheDir/images'

# Lotus Docs configuration
[params.docs]

    # Set the default HTML title for documentation pages/sections
    # (separate from the root Hugo site title)
    title = "Lotus Docs"

    # Pathname for the documentation site
    # e.g., if you change this, additional theme config may be needed
    pathName = "docs"

    # Site accent color for links, buttons, icons
    # Options: blue (default), green, red, yellow, emerald, cardinal, magenta, cyan
    themeColor = "magenta"

[[module.mounts]]
    source = 'images'
    target = 'static/images'
